### ISSUE TITLE
Car il est important de maintenir le lien

### ISSUE THREAD

**Issue by the2ne** [desbenoit/ChallengeDuBerger#44]
Bonjour,

Quelques liens externes sont obsolètes :
- les deux liens dans le paragraphe de présentation du README pointent vers le même article de blog
- le lien vers les formules en anglais ne semble plus d'actualité

Ah ! Et au cas où on ne se reverrait pas, une bonne soirée et une excellente nuit !

**Comment by desbenoit** [comment]
Un grand merci à vous 

Bonne fin de week-end, 

Sébastien
